//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUADRES_DIARIOS
    {
        public string FECHA { get; set; }
        public decimal VALOR_PAGADO { get; set; }
        public decimal VALOR_ANULADO { get; set; }
        public decimal VALOR_TOTAL { get; set; }
        public Nullable<decimal> VALOR_DESCUENTO { get; set; }
    }
}
