//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BD_JSYSEntities : DbContext
    {
        public BD_JSYSEntities()
            : base("name=BD_JSYSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CLIENTES> CLIENTES { get; set; }
        public virtual DbSet<CUADRES_DIARIOS> CUADRES_DIARIOS { get; set; }
        public virtual DbSet<DETALLES_CUOTAS> DETALLES_CUOTAS { get; set; }
        public virtual DbSet<EMPRESA> EMPRESA { get; set; }
        public virtual DbSet<ENCABEZADO_CUOTAS> ENCABEZADO_CUOTAS { get; set; }
        public virtual DbSet<ESTADO_FACTURAS> ESTADO_FACTURAS { get; set; }
        public virtual DbSet<FACTURAS> FACTURAS { get; set; }
        public virtual DbSet<PANTALLAS> PANTALLAS { get; set; }
        public virtual DbSet<PERMISOS> PERMISOS { get; set; }
        public virtual DbSet<RECIBOS_COBRADOS> RECIBOS_COBRADOS { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TIPOS_IDENTIFICACIONES> TIPOS_IDENTIFICACIONES { get; set; }
        public virtual DbSet<USUARIOS> USUARIOS { get; set; }
    
        public virtual int SP_ARTICULOS(Nullable<int> iD_ARTICULO, string rEFERENCIA, string dESCRIPCION, Nullable<int> cANTIDAD, Nullable<decimal> pRECIO_COMPRA, Nullable<decimal> pRECIO_VENTA1, Nullable<decimal> pRECIO_VENTA2, Nullable<decimal> pRECIO_VENTA3, string aPLICA_ITBIS, string eSTADO, string cREADO_POR, Nullable<System.DateTime> fECHA_CREADO, string aCCION, string cONDICION)
        {
            var iD_ARTICULOParameter = iD_ARTICULO.HasValue ?
                new ObjectParameter("ID_ARTICULO", iD_ARTICULO) :
                new ObjectParameter("ID_ARTICULO", typeof(int));
    
            var rEFERENCIAParameter = rEFERENCIA != null ?
                new ObjectParameter("REFERENCIA", rEFERENCIA) :
                new ObjectParameter("REFERENCIA", typeof(string));
    
            var dESCRIPCIONParameter = dESCRIPCION != null ?
                new ObjectParameter("DESCRIPCION", dESCRIPCION) :
                new ObjectParameter("DESCRIPCION", typeof(string));
    
            var cANTIDADParameter = cANTIDAD.HasValue ?
                new ObjectParameter("CANTIDAD", cANTIDAD) :
                new ObjectParameter("CANTIDAD", typeof(int));
    
            var pRECIO_COMPRAParameter = pRECIO_COMPRA.HasValue ?
                new ObjectParameter("PRECIO_COMPRA", pRECIO_COMPRA) :
                new ObjectParameter("PRECIO_COMPRA", typeof(decimal));
    
            var pRECIO_VENTA1Parameter = pRECIO_VENTA1.HasValue ?
                new ObjectParameter("PRECIO_VENTA1", pRECIO_VENTA1) :
                new ObjectParameter("PRECIO_VENTA1", typeof(decimal));
    
            var pRECIO_VENTA2Parameter = pRECIO_VENTA2.HasValue ?
                new ObjectParameter("PRECIO_VENTA2", pRECIO_VENTA2) :
                new ObjectParameter("PRECIO_VENTA2", typeof(decimal));
    
            var pRECIO_VENTA3Parameter = pRECIO_VENTA3.HasValue ?
                new ObjectParameter("PRECIO_VENTA3", pRECIO_VENTA3) :
                new ObjectParameter("PRECIO_VENTA3", typeof(decimal));
    
            var aPLICA_ITBISParameter = aPLICA_ITBIS != null ?
                new ObjectParameter("APLICA_ITBIS", aPLICA_ITBIS) :
                new ObjectParameter("APLICA_ITBIS", typeof(string));
    
            var eSTADOParameter = eSTADO != null ?
                new ObjectParameter("ESTADO", eSTADO) :
                new ObjectParameter("ESTADO", typeof(string));
    
            var cREADO_PORParameter = cREADO_POR != null ?
                new ObjectParameter("CREADO_POR", cREADO_POR) :
                new ObjectParameter("CREADO_POR", typeof(string));
    
            var fECHA_CREADOParameter = fECHA_CREADO.HasValue ?
                new ObjectParameter("FECHA_CREADO", fECHA_CREADO) :
                new ObjectParameter("FECHA_CREADO", typeof(System.DateTime));
    
            var aCCIONParameter = aCCION != null ?
                new ObjectParameter("ACCION", aCCION) :
                new ObjectParameter("ACCION", typeof(string));
    
            var cONDICIONParameter = cONDICION != null ?
                new ObjectParameter("CONDICION", cONDICION) :
                new ObjectParameter("CONDICION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ARTICULOS", iD_ARTICULOParameter, rEFERENCIAParameter, dESCRIPCIONParameter, cANTIDADParameter, pRECIO_COMPRAParameter, pRECIO_VENTA1Parameter, pRECIO_VENTA2Parameter, pRECIO_VENTA3Parameter, aPLICA_ITBISParameter, eSTADOParameter, cREADO_PORParameter, fECHA_CREADOParameter, aCCIONParameter, cONDICIONParameter);
        }
    
        public virtual int SP_CLIENTES(Nullable<int> iD_CLIENTE, string nOMBRE, Nullable<int> iD_TIPO_IDENTIFICACION, string nUMERO_IDENTIFICACION, string dIRECCION, string tELEFONO, string cELULAR, string eMAIL, string eSTADO, Nullable<decimal> lIMITE_CREDITO, string cREADO_POR, Nullable<System.DateTime> fECHA_CREADO, string aCCION, string cONDICION)
        {
            var iD_CLIENTEParameter = iD_CLIENTE.HasValue ?
                new ObjectParameter("ID_CLIENTE", iD_CLIENTE) :
                new ObjectParameter("ID_CLIENTE", typeof(int));
    
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var iD_TIPO_IDENTIFICACIONParameter = iD_TIPO_IDENTIFICACION.HasValue ?
                new ObjectParameter("ID_TIPO_IDENTIFICACION", iD_TIPO_IDENTIFICACION) :
                new ObjectParameter("ID_TIPO_IDENTIFICACION", typeof(int));
    
            var nUMERO_IDENTIFICACIONParameter = nUMERO_IDENTIFICACION != null ?
                new ObjectParameter("NUMERO_IDENTIFICACION", nUMERO_IDENTIFICACION) :
                new ObjectParameter("NUMERO_IDENTIFICACION", typeof(string));
    
            var dIRECCIONParameter = dIRECCION != null ?
                new ObjectParameter("DIRECCION", dIRECCION) :
                new ObjectParameter("DIRECCION", typeof(string));
    
            var tELEFONOParameter = tELEFONO != null ?
                new ObjectParameter("TELEFONO", tELEFONO) :
                new ObjectParameter("TELEFONO", typeof(string));
    
            var cELULARParameter = cELULAR != null ?
                new ObjectParameter("CELULAR", cELULAR) :
                new ObjectParameter("CELULAR", typeof(string));
    
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            var eSTADOParameter = eSTADO != null ?
                new ObjectParameter("ESTADO", eSTADO) :
                new ObjectParameter("ESTADO", typeof(string));
    
            var lIMITE_CREDITOParameter = lIMITE_CREDITO.HasValue ?
                new ObjectParameter("LIMITE_CREDITO", lIMITE_CREDITO) :
                new ObjectParameter("LIMITE_CREDITO", typeof(decimal));
    
            var cREADO_PORParameter = cREADO_POR != null ?
                new ObjectParameter("CREADO_POR", cREADO_POR) :
                new ObjectParameter("CREADO_POR", typeof(string));
    
            var fECHA_CREADOParameter = fECHA_CREADO.HasValue ?
                new ObjectParameter("FECHA_CREADO", fECHA_CREADO) :
                new ObjectParameter("FECHA_CREADO", typeof(System.DateTime));
    
            var aCCIONParameter = aCCION != null ?
                new ObjectParameter("ACCION", aCCION) :
                new ObjectParameter("ACCION", typeof(string));
    
            var cONDICIONParameter = cONDICION != null ?
                new ObjectParameter("CONDICION", cONDICION) :
                new ObjectParameter("CONDICION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CLIENTES", iD_CLIENTEParameter, nOMBREParameter, iD_TIPO_IDENTIFICACIONParameter, nUMERO_IDENTIFICACIONParameter, dIRECCIONParameter, tELEFONOParameter, cELULARParameter, eMAILParameter, eSTADOParameter, lIMITE_CREDITOParameter, cREADO_PORParameter, fECHA_CREADOParameter, aCCIONParameter, cONDICIONParameter);
        }
    
        public virtual int SP_COBRADORES(Nullable<int> iD_COBRADOR, string nOMBRE, Nullable<int> iD_TIPO_IDENTIFICACION, string nUMERO_IDENTIFICACION, string eSTADO, string sEXO, string cREADO_POR, Nullable<System.DateTime> fECHA_CREADO, string aCCION, string cONDICION)
        {
            var iD_COBRADORParameter = iD_COBRADOR.HasValue ?
                new ObjectParameter("ID_COBRADOR", iD_COBRADOR) :
                new ObjectParameter("ID_COBRADOR", typeof(int));
    
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var iD_TIPO_IDENTIFICACIONParameter = iD_TIPO_IDENTIFICACION.HasValue ?
                new ObjectParameter("ID_TIPO_IDENTIFICACION", iD_TIPO_IDENTIFICACION) :
                new ObjectParameter("ID_TIPO_IDENTIFICACION", typeof(int));
    
            var nUMERO_IDENTIFICACIONParameter = nUMERO_IDENTIFICACION != null ?
                new ObjectParameter("NUMERO_IDENTIFICACION", nUMERO_IDENTIFICACION) :
                new ObjectParameter("NUMERO_IDENTIFICACION", typeof(string));
    
            var eSTADOParameter = eSTADO != null ?
                new ObjectParameter("ESTADO", eSTADO) :
                new ObjectParameter("ESTADO", typeof(string));
    
            var sEXOParameter = sEXO != null ?
                new ObjectParameter("SEXO", sEXO) :
                new ObjectParameter("SEXO", typeof(string));
    
            var cREADO_PORParameter = cREADO_POR != null ?
                new ObjectParameter("CREADO_POR", cREADO_POR) :
                new ObjectParameter("CREADO_POR", typeof(string));
    
            var fECHA_CREADOParameter = fECHA_CREADO.HasValue ?
                new ObjectParameter("FECHA_CREADO", fECHA_CREADO) :
                new ObjectParameter("FECHA_CREADO", typeof(System.DateTime));
    
            var aCCIONParameter = aCCION != null ?
                new ObjectParameter("ACCION", aCCION) :
                new ObjectParameter("ACCION", typeof(string));
    
            var cONDICIONParameter = cONDICION != null ?
                new ObjectParameter("CONDICION", cONDICION) :
                new ObjectParameter("CONDICION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_COBRADORES", iD_COBRADORParameter, nOMBREParameter, iD_TIPO_IDENTIFICACIONParameter, nUMERO_IDENTIFICACIONParameter, eSTADOParameter, sEXOParameter, cREADO_PORParameter, fECHA_CREADOParameter, aCCIONParameter, cONDICIONParameter);
        }
    
        public virtual ObjectResult<SP_EMPRESA_Result> SP_EMPRESA(Nullable<int> iD_EMPRESA, string eMPRESA, string dIRECCION, Nullable<int> iD_TIPO_IDENTIFICACION, string nUMERO_IDENTIFICACION, string tELEFONO, string cELULAR, string fAX, string eMAIL, string pAGINA_WEB, string eSLOGAN, Nullable<int> iTBIS, string iMPRESORA, byte[] lOGO, string aCCION, string cONDICION)
        {
            var iD_EMPRESAParameter = iD_EMPRESA.HasValue ?
                new ObjectParameter("ID_EMPRESA", iD_EMPRESA) :
                new ObjectParameter("ID_EMPRESA", typeof(int));
    
            var eMPRESAParameter = eMPRESA != null ?
                new ObjectParameter("EMPRESA", eMPRESA) :
                new ObjectParameter("EMPRESA", typeof(string));
    
            var dIRECCIONParameter = dIRECCION != null ?
                new ObjectParameter("DIRECCION", dIRECCION) :
                new ObjectParameter("DIRECCION", typeof(string));
    
            var iD_TIPO_IDENTIFICACIONParameter = iD_TIPO_IDENTIFICACION.HasValue ?
                new ObjectParameter("ID_TIPO_IDENTIFICACION", iD_TIPO_IDENTIFICACION) :
                new ObjectParameter("ID_TIPO_IDENTIFICACION", typeof(int));
    
            var nUMERO_IDENTIFICACIONParameter = nUMERO_IDENTIFICACION != null ?
                new ObjectParameter("NUMERO_IDENTIFICACION", nUMERO_IDENTIFICACION) :
                new ObjectParameter("NUMERO_IDENTIFICACION", typeof(string));
    
            var tELEFONOParameter = tELEFONO != null ?
                new ObjectParameter("TELEFONO", tELEFONO) :
                new ObjectParameter("TELEFONO", typeof(string));
    
            var cELULARParameter = cELULAR != null ?
                new ObjectParameter("CELULAR", cELULAR) :
                new ObjectParameter("CELULAR", typeof(string));
    
            var fAXParameter = fAX != null ?
                new ObjectParameter("FAX", fAX) :
                new ObjectParameter("FAX", typeof(string));
    
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            var pAGINA_WEBParameter = pAGINA_WEB != null ?
                new ObjectParameter("PAGINA_WEB", pAGINA_WEB) :
                new ObjectParameter("PAGINA_WEB", typeof(string));
    
            var eSLOGANParameter = eSLOGAN != null ?
                new ObjectParameter("ESLOGAN", eSLOGAN) :
                new ObjectParameter("ESLOGAN", typeof(string));
    
            var iTBISParameter = iTBIS.HasValue ?
                new ObjectParameter("ITBIS", iTBIS) :
                new ObjectParameter("ITBIS", typeof(int));
    
            var iMPRESORAParameter = iMPRESORA != null ?
                new ObjectParameter("IMPRESORA", iMPRESORA) :
                new ObjectParameter("IMPRESORA", typeof(string));
    
            var lOGOParameter = lOGO != null ?
                new ObjectParameter("LOGO", lOGO) :
                new ObjectParameter("LOGO", typeof(byte[]));
    
            var aCCIONParameter = aCCION != null ?
                new ObjectParameter("ACCION", aCCION) :
                new ObjectParameter("ACCION", typeof(string));
    
            var cONDICIONParameter = cONDICION != null ?
                new ObjectParameter("CONDICION", cONDICION) :
                new ObjectParameter("CONDICION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_EMPRESA_Result>("SP_EMPRESA", iD_EMPRESAParameter, eMPRESAParameter, dIRECCIONParameter, iD_TIPO_IDENTIFICACIONParameter, nUMERO_IDENTIFICACIONParameter, tELEFONOParameter, cELULARParameter, fAXParameter, eMAILParameter, pAGINA_WEBParameter, eSLOGANParameter, iTBISParameter, iMPRESORAParameter, lOGOParameter, aCCIONParameter, cONDICIONParameter);
        }
    
        public virtual int SP_FACTURAS(Nullable<int> iD_FACTURA, Nullable<int> nUMERO_CONTRATO, Nullable<System.DateTime> fECHA, Nullable<int> iD_CLIENTE, Nullable<int> iD_COBRADOR, Nullable<int> iD_VENDEDOR, string nUMERO_LOTERIA, Nullable<int> nUMERO_CUOTAS, Nullable<decimal> mONTO_TOTAL, Nullable<decimal> mONTO_PAGADO, Nullable<decimal> mONTO_PENDIENTE, string eNTREGADA, string fECHA_ENTREGA, string rUTA_COBRADOR, string eSTADO, string oBSERVACION, string cREADO_POR, Nullable<System.DateTime> fECHA_CREADO, string aCCION, string cONDICION, Nullable<int> iD_FACTURA_DETALLE, Nullable<int> iD_ARTICULO_DETALLE, Nullable<int> cANTIDAD_DETALLE, Nullable<decimal> pRECIO_DETALLE, Nullable<decimal> mONTO_ITBIS_DETALLE, Nullable<decimal> sUB_TOTAL_DETALLE, Nullable<decimal> mONTO_TOTAL_DETALLE, string eNTREGADO_DETALLE, Nullable<int> iD_FACTURA_CUOTA, Nullable<int> nUMERO_CUOTA, Nullable<System.DateTime> fECHA_CUOTA, Nullable<decimal> mONTO_CUOTA, Nullable<decimal> mONTO_PAGADO_CUOTA, Nullable<decimal> mONTO_PENDIENTE_CUOTA)
        {
            var iD_FACTURAParameter = iD_FACTURA.HasValue ?
                new ObjectParameter("ID_FACTURA", iD_FACTURA) :
                new ObjectParameter("ID_FACTURA", typeof(int));
    
            var nUMERO_CONTRATOParameter = nUMERO_CONTRATO.HasValue ?
                new ObjectParameter("NUMERO_CONTRATO", nUMERO_CONTRATO) :
                new ObjectParameter("NUMERO_CONTRATO", typeof(int));
    
            var fECHAParameter = fECHA.HasValue ?
                new ObjectParameter("FECHA", fECHA) :
                new ObjectParameter("FECHA", typeof(System.DateTime));
    
            var iD_CLIENTEParameter = iD_CLIENTE.HasValue ?
                new ObjectParameter("ID_CLIENTE", iD_CLIENTE) :
                new ObjectParameter("ID_CLIENTE", typeof(int));
    
            var iD_COBRADORParameter = iD_COBRADOR.HasValue ?
                new ObjectParameter("ID_COBRADOR", iD_COBRADOR) :
                new ObjectParameter("ID_COBRADOR", typeof(int));
    
            var iD_VENDEDORParameter = iD_VENDEDOR.HasValue ?
                new ObjectParameter("ID_VENDEDOR", iD_VENDEDOR) :
                new ObjectParameter("ID_VENDEDOR", typeof(int));
    
            var nUMERO_LOTERIAParameter = nUMERO_LOTERIA != null ?
                new ObjectParameter("NUMERO_LOTERIA", nUMERO_LOTERIA) :
                new ObjectParameter("NUMERO_LOTERIA", typeof(string));
    
            var nUMERO_CUOTASParameter = nUMERO_CUOTAS.HasValue ?
                new ObjectParameter("NUMERO_CUOTAS", nUMERO_CUOTAS) :
                new ObjectParameter("NUMERO_CUOTAS", typeof(int));
    
            var mONTO_TOTALParameter = mONTO_TOTAL.HasValue ?
                new ObjectParameter("MONTO_TOTAL", mONTO_TOTAL) :
                new ObjectParameter("MONTO_TOTAL", typeof(decimal));
    
            var mONTO_PAGADOParameter = mONTO_PAGADO.HasValue ?
                new ObjectParameter("MONTO_PAGADO", mONTO_PAGADO) :
                new ObjectParameter("MONTO_PAGADO", typeof(decimal));
    
            var mONTO_PENDIENTEParameter = mONTO_PENDIENTE.HasValue ?
                new ObjectParameter("MONTO_PENDIENTE", mONTO_PENDIENTE) :
                new ObjectParameter("MONTO_PENDIENTE", typeof(decimal));
    
            var eNTREGADAParameter = eNTREGADA != null ?
                new ObjectParameter("ENTREGADA", eNTREGADA) :
                new ObjectParameter("ENTREGADA", typeof(string));
    
            var fECHA_ENTREGAParameter = fECHA_ENTREGA != null ?
                new ObjectParameter("FECHA_ENTREGA", fECHA_ENTREGA) :
                new ObjectParameter("FECHA_ENTREGA", typeof(string));
    
            var rUTA_COBRADORParameter = rUTA_COBRADOR != null ?
                new ObjectParameter("RUTA_COBRADOR", rUTA_COBRADOR) :
                new ObjectParameter("RUTA_COBRADOR", typeof(string));
    
            var eSTADOParameter = eSTADO != null ?
                new ObjectParameter("ESTADO", eSTADO) :
                new ObjectParameter("ESTADO", typeof(string));
    
            var oBSERVACIONParameter = oBSERVACION != null ?
                new ObjectParameter("OBSERVACION", oBSERVACION) :
                new ObjectParameter("OBSERVACION", typeof(string));
    
            var cREADO_PORParameter = cREADO_POR != null ?
                new ObjectParameter("CREADO_POR", cREADO_POR) :
                new ObjectParameter("CREADO_POR", typeof(string));
    
            var fECHA_CREADOParameter = fECHA_CREADO.HasValue ?
                new ObjectParameter("FECHA_CREADO", fECHA_CREADO) :
                new ObjectParameter("FECHA_CREADO", typeof(System.DateTime));
    
            var aCCIONParameter = aCCION != null ?
                new ObjectParameter("ACCION", aCCION) :
                new ObjectParameter("ACCION", typeof(string));
    
            var cONDICIONParameter = cONDICION != null ?
                new ObjectParameter("CONDICION", cONDICION) :
                new ObjectParameter("CONDICION", typeof(string));
    
            var iD_FACTURA_DETALLEParameter = iD_FACTURA_DETALLE.HasValue ?
                new ObjectParameter("ID_FACTURA_DETALLE", iD_FACTURA_DETALLE) :
                new ObjectParameter("ID_FACTURA_DETALLE", typeof(int));
    
            var iD_ARTICULO_DETALLEParameter = iD_ARTICULO_DETALLE.HasValue ?
                new ObjectParameter("ID_ARTICULO_DETALLE", iD_ARTICULO_DETALLE) :
                new ObjectParameter("ID_ARTICULO_DETALLE", typeof(int));
    
            var cANTIDAD_DETALLEParameter = cANTIDAD_DETALLE.HasValue ?
                new ObjectParameter("CANTIDAD_DETALLE", cANTIDAD_DETALLE) :
                new ObjectParameter("CANTIDAD_DETALLE", typeof(int));
    
            var pRECIO_DETALLEParameter = pRECIO_DETALLE.HasValue ?
                new ObjectParameter("PRECIO_DETALLE", pRECIO_DETALLE) :
                new ObjectParameter("PRECIO_DETALLE", typeof(decimal));
    
            var mONTO_ITBIS_DETALLEParameter = mONTO_ITBIS_DETALLE.HasValue ?
                new ObjectParameter("MONTO_ITBIS_DETALLE", mONTO_ITBIS_DETALLE) :
                new ObjectParameter("MONTO_ITBIS_DETALLE", typeof(decimal));
    
            var sUB_TOTAL_DETALLEParameter = sUB_TOTAL_DETALLE.HasValue ?
                new ObjectParameter("SUB_TOTAL_DETALLE", sUB_TOTAL_DETALLE) :
                new ObjectParameter("SUB_TOTAL_DETALLE", typeof(decimal));
    
            var mONTO_TOTAL_DETALLEParameter = mONTO_TOTAL_DETALLE.HasValue ?
                new ObjectParameter("MONTO_TOTAL_DETALLE", mONTO_TOTAL_DETALLE) :
                new ObjectParameter("MONTO_TOTAL_DETALLE", typeof(decimal));
    
            var eNTREGADO_DETALLEParameter = eNTREGADO_DETALLE != null ?
                new ObjectParameter("ENTREGADO_DETALLE", eNTREGADO_DETALLE) :
                new ObjectParameter("ENTREGADO_DETALLE", typeof(string));
    
            var iD_FACTURA_CUOTAParameter = iD_FACTURA_CUOTA.HasValue ?
                new ObjectParameter("ID_FACTURA_CUOTA", iD_FACTURA_CUOTA) :
                new ObjectParameter("ID_FACTURA_CUOTA", typeof(int));
    
            var nUMERO_CUOTAParameter = nUMERO_CUOTA.HasValue ?
                new ObjectParameter("NUMERO_CUOTA", nUMERO_CUOTA) :
                new ObjectParameter("NUMERO_CUOTA", typeof(int));
    
            var fECHA_CUOTAParameter = fECHA_CUOTA.HasValue ?
                new ObjectParameter("FECHA_CUOTA", fECHA_CUOTA) :
                new ObjectParameter("FECHA_CUOTA", typeof(System.DateTime));
    
            var mONTO_CUOTAParameter = mONTO_CUOTA.HasValue ?
                new ObjectParameter("MONTO_CUOTA", mONTO_CUOTA) :
                new ObjectParameter("MONTO_CUOTA", typeof(decimal));
    
            var mONTO_PAGADO_CUOTAParameter = mONTO_PAGADO_CUOTA.HasValue ?
                new ObjectParameter("MONTO_PAGADO_CUOTA", mONTO_PAGADO_CUOTA) :
                new ObjectParameter("MONTO_PAGADO_CUOTA", typeof(decimal));
    
            var mONTO_PENDIENTE_CUOTAParameter = mONTO_PENDIENTE_CUOTA.HasValue ?
                new ObjectParameter("MONTO_PENDIENTE_CUOTA", mONTO_PENDIENTE_CUOTA) :
                new ObjectParameter("MONTO_PENDIENTE_CUOTA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_FACTURAS", iD_FACTURAParameter, nUMERO_CONTRATOParameter, fECHAParameter, iD_CLIENTEParameter, iD_COBRADORParameter, iD_VENDEDORParameter, nUMERO_LOTERIAParameter, nUMERO_CUOTASParameter, mONTO_TOTALParameter, mONTO_PAGADOParameter, mONTO_PENDIENTEParameter, eNTREGADAParameter, fECHA_ENTREGAParameter, rUTA_COBRADORParameter, eSTADOParameter, oBSERVACIONParameter, cREADO_PORParameter, fECHA_CREADOParameter, aCCIONParameter, cONDICIONParameter, iD_FACTURA_DETALLEParameter, iD_ARTICULO_DETALLEParameter, cANTIDAD_DETALLEParameter, pRECIO_DETALLEParameter, mONTO_ITBIS_DETALLEParameter, sUB_TOTAL_DETALLEParameter, mONTO_TOTAL_DETALLEParameter, eNTREGADO_DETALLEParameter, iD_FACTURA_CUOTAParameter, nUMERO_CUOTAParameter, fECHA_CUOTAParameter, mONTO_CUOTAParameter, mONTO_PAGADO_CUOTAParameter, mONTO_PENDIENTE_CUOTAParameter);
        }
    
        public virtual int SP_LLENAR_COMBOBOX(string tABLA, string vALOR_MOSTRAR, string vALOR_CODIGO, string cONDICION)
        {
            var tABLAParameter = tABLA != null ?
                new ObjectParameter("TABLA", tABLA) :
                new ObjectParameter("TABLA", typeof(string));
    
            var vALOR_MOSTRARParameter = vALOR_MOSTRAR != null ?
                new ObjectParameter("VALOR_MOSTRAR", vALOR_MOSTRAR) :
                new ObjectParameter("VALOR_MOSTRAR", typeof(string));
    
            var vALOR_CODIGOParameter = vALOR_CODIGO != null ?
                new ObjectParameter("VALOR_CODIGO", vALOR_CODIGO) :
                new ObjectParameter("VALOR_CODIGO", typeof(string));
    
            var cONDICIONParameter = cONDICION != null ?
                new ObjectParameter("CONDICION", cONDICION) :
                new ObjectParameter("CONDICION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_LLENAR_COMBOBOX", tABLAParameter, vALOR_MOSTRARParameter, vALOR_CODIGOParameter, cONDICIONParameter);
        }
    
        public virtual int SP_USUARIOS(Nullable<int> iD_USUARIO, string uSUARIO, string cLAVE, string nOMBRE, string eSTADO, string sEXO, string cREADO_POR, Nullable<System.DateTime> fECHA_CREADO, string aCCION, string cONDICION)
        {
            var iD_USUARIOParameter = iD_USUARIO.HasValue ?
                new ObjectParameter("ID_USUARIO", iD_USUARIO) :
                new ObjectParameter("ID_USUARIO", typeof(int));
    
            var uSUARIOParameter = uSUARIO != null ?
                new ObjectParameter("USUARIO", uSUARIO) :
                new ObjectParameter("USUARIO", typeof(string));
    
            var cLAVEParameter = cLAVE != null ?
                new ObjectParameter("CLAVE", cLAVE) :
                new ObjectParameter("CLAVE", typeof(string));
    
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var eSTADOParameter = eSTADO != null ?
                new ObjectParameter("ESTADO", eSTADO) :
                new ObjectParameter("ESTADO", typeof(string));
    
            var sEXOParameter = sEXO != null ?
                new ObjectParameter("SEXO", sEXO) :
                new ObjectParameter("SEXO", typeof(string));
    
            var cREADO_PORParameter = cREADO_POR != null ?
                new ObjectParameter("CREADO_POR", cREADO_POR) :
                new ObjectParameter("CREADO_POR", typeof(string));
    
            var fECHA_CREADOParameter = fECHA_CREADO.HasValue ?
                new ObjectParameter("FECHA_CREADO", fECHA_CREADO) :
                new ObjectParameter("FECHA_CREADO", typeof(System.DateTime));
    
            var aCCIONParameter = aCCION != null ?
                new ObjectParameter("ACCION", aCCION) :
                new ObjectParameter("ACCION", typeof(string));
    
            var cONDICIONParameter = cONDICION != null ?
                new ObjectParameter("CONDICION", cONDICION) :
                new ObjectParameter("CONDICION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_USUARIOS", iD_USUARIOParameter, uSUARIOParameter, cLAVEParameter, nOMBREParameter, eSTADOParameter, sEXOParameter, cREADO_PORParameter, fECHA_CREADOParameter, aCCIONParameter, cONDICIONParameter);
        }
    
        public virtual int SP_VENDEDORES(Nullable<int> iD_VENDEDOR, string nOMBRE, Nullable<int> iD_TIPO_IDENTIFICACION, string nUMERO_IDENTIFICACION, string eSTADO, string sEXO, string cREADO_POR, Nullable<System.DateTime> fECHA_CREADO, string aCCION, string cONDICION)
        {
            var iD_VENDEDORParameter = iD_VENDEDOR.HasValue ?
                new ObjectParameter("ID_VENDEDOR", iD_VENDEDOR) :
                new ObjectParameter("ID_VENDEDOR", typeof(int));
    
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var iD_TIPO_IDENTIFICACIONParameter = iD_TIPO_IDENTIFICACION.HasValue ?
                new ObjectParameter("ID_TIPO_IDENTIFICACION", iD_TIPO_IDENTIFICACION) :
                new ObjectParameter("ID_TIPO_IDENTIFICACION", typeof(int));
    
            var nUMERO_IDENTIFICACIONParameter = nUMERO_IDENTIFICACION != null ?
                new ObjectParameter("NUMERO_IDENTIFICACION", nUMERO_IDENTIFICACION) :
                new ObjectParameter("NUMERO_IDENTIFICACION", typeof(string));
    
            var eSTADOParameter = eSTADO != null ?
                new ObjectParameter("ESTADO", eSTADO) :
                new ObjectParameter("ESTADO", typeof(string));
    
            var sEXOParameter = sEXO != null ?
                new ObjectParameter("SEXO", sEXO) :
                new ObjectParameter("SEXO", typeof(string));
    
            var cREADO_PORParameter = cREADO_POR != null ?
                new ObjectParameter("CREADO_POR", cREADO_POR) :
                new ObjectParameter("CREADO_POR", typeof(string));
    
            var fECHA_CREADOParameter = fECHA_CREADO.HasValue ?
                new ObjectParameter("FECHA_CREADO", fECHA_CREADO) :
                new ObjectParameter("FECHA_CREADO", typeof(System.DateTime));
    
            var aCCIONParameter = aCCION != null ?
                new ObjectParameter("ACCION", aCCION) :
                new ObjectParameter("ACCION", typeof(string));
    
            var cONDICIONParameter = cONDICION != null ?
                new ObjectParameter("CONDICION", cONDICION) :
                new ObjectParameter("CONDICION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_VENDEDORES", iD_VENDEDORParameter, nOMBREParameter, iD_TIPO_IDENTIFICACIONParameter, nUMERO_IDENTIFICACIONParameter, eSTADOParameter, sEXOParameter, cREADO_PORParameter, fECHA_CREADOParameter, aCCIONParameter, cONDICIONParameter);
        }
    }
}
